window.panchangData = {

"2026-07-21": {
  tithi: "आषाढ़ शुक्ल अष्टमी",
  nakshatra: "चित्रा",
  yog: "सिद्ध",
  karan: "विष्टि / बव",
  rahuKaal: "03:50 PM - 05:32 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "भद्रा समाप्त",
  sunrise: "05:40 AM",
  sunset: "07:14 PM",
  moonrise: "12:32 PM",
  moonset: "11:35 PM",
  rashi: "कन्या",
  fast: ["मासिक दुर्गाष्टमी"],
  festival: "पार्वती जयंती",
  governmentHoliday: ""
},

"2026-07-22": {
  tithi: "आषाढ़ शुक्ल नवमी",
  nakshatra: "स्वाती",
  yog: "साध्य",
  karan: "बालव",
  rahuKaal: "12:25 PM - 02:07 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:40 AM",
  sunset: "07:13 PM",
  moonrise: "01:18 PM",
  moonset: "12:20 AM",
  rashi: "तुला",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-07-23": {
  tithi: "आषाढ़ शुक्ल दशमी",
  nakshatra: "विशाखा",
  yog: "शुभ",
  karan: "तैतिल",
  rahuKaal: "01:45 PM - 03:27 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:41 AM",
  sunset: "07:13 PM",
  moonrise: "02:05 PM",
  moonset: "01:05 AM",
  rashi: "तुला",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-07-24": {
  tithi: "आषाढ़ शुक्ल एकादशी",
  nakshatra: "अनुराधा",
  yog: "ब्रह्म",
  karan: "वणिज",
  rahuKaal: "10:30 AM - 12:12 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:41 AM",
  sunset: "07:12 PM",
  moonrise: "02:52 PM",
  moonset: "01:50 AM",
  rashi: "वृश्चिक",
  fast: ["देवशयनी एकादशी व्रत"],
  festival: "देवशयनी एकादशी",
  governmentHoliday: ""
},

"2026-07-25": {
  tithi: "आषाढ़ शुक्ल द्वादशी",
  nakshatra: "ज्येष्ठा",
  yog: "इन्द्र",
  karan: "बव",
  rahuKaal: "09:00 AM - 10:42 AM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:42 AM",
  sunset: "07:12 PM",
  moonrise: "03:39 PM",
  moonset: "02:36 AM",
  rashi: "वृश्चिक",
  fast: ["व्रत पारण"],
  festival: "देवशयनी एकादशी पारण",
  governmentHoliday: ""
},

"2026-07-26": {
  tithi: "आषाढ़ शुक्ल त्रयोदशी",
  nakshatra: "मूल",
  yog: "वैधृति",
  karan: "कौलव",
  rahuKaal: "05:30 PM - 07:12 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:42 AM",
  sunset: "07:11 PM",
  moonrise: "04:26 PM",
  moonset: "03:22 AM",
  rashi: "धनु",
  fast: [],
  festival: "प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-07-27": {
  tithi: "आषाढ़ शुक्ल चतुर्दशी",
  nakshatra: "पूर्वाषाढ़ा",
  yog: "विष्कम्भ",
  karan: "गर",
  rahuKaal: "08:30 AM - 10:12 AM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:43 AM",
  sunset: "07:10 PM",
  moonrise: "05:13 PM",
  moonset: "04:10 AM",
  rashi: "धनु",
  fast: ["मासिक शिवरात्रि"],
  festival: "मासिक शिवरात्रि",
  governmentHoliday: ""
},

"2026-07-28": {
  tithi: "आषाढ़ पूर्णिमा",
  nakshatra: "उत्तराषाढ़ा",
  yog: "प्रीति",
  karan: "विष्टि",
  rahuKaal: "03:45 PM - 05:27 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "पूर्णिमा",
  sunrise: "05:43 AM",
  sunset: "07:10 PM",
  moonrise: "06:01 PM",
  moonset: "04:58 AM",
  rashi: "मकर",
  fast: ["गुरु पूर्णिमा व्रत"],
  festival: "गुरु पूर्णिमा",
  governmentHoliday: ""
},

"2026-07-29": {
  tithi: "श्रावण कृष्ण प्रतिपदा",
  nakshatra: "श्रवण",
  yog: "आयुष्मान",
  karan: "बव",
  rahuKaal: "12:20 PM - 02:02 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:44 AM",
  sunset: "07:09 PM",
  moonrise: "06:49 PM",
  moonset: "05:48 AM",
  rashi: "मकर",
  fast: [],
  festival: "श्रावण मास प्रारंभ",
  governmentHoliday: ""
},

"2026-07-30": {
  tithi: "श्रावण कृष्ण द्वितीया",
  nakshatra: "धनिष्ठा",
  yog: "सौभाग्य",
  karan: "कौलव",
  rahuKaal: "01:40 PM - 03:22 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:44 AM",
  sunset: "07:08 PM",
  moonrise: "07:37 PM",
  moonset: "06:39 AM",
  rashi: "कुंभ",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-07-31": {
  tithi: "श्रावण कृष्ण तृतीया",
  nakshatra: "शतभिषा",
  yog: "शोभन",
  karan: "तैतिल",
  rahuKaal: "10:35 AM - 12:17 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:45 AM",
  sunset: "07:08 PM",
  moonrise: "08:26 PM",
  moonset: "07:32 AM",
  rashi: "कुंभ",
  fast: [],
  festival: "",
  governmentHoliday: ""
},


"2026-08-01": {
  tithi: "श्रावण कृष्ण चतुर्थी",
  nakshatra: "पूर्वाभाद्रपद",
  yog: "अतिगंड",
  karan: "वणिज",
  rahuKaal: "09:00 AM - 10:42 AM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:45 AM",
  sunset: "07:07 PM",
  moonrise: "09:14 PM",
  moonset: "08:26 AM",
  rashi: "कुंभ",
  fast: ["संकष्टी चतुर्थी व्रत"],
  festival: "संकष्टी गणेश चतुर्थी",
  governmentHoliday: ""
},

"2026-08-02": {
  tithi: "श्रावण कृष्ण पञ्चमी",
  nakshatra: "उत्तराभाद्रपद",
  yog: "सुकर्मा",
  karan: "बव",
  rahuKaal: "05:25 PM - 07:07 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:46 AM",
  sunset: "07:07 PM",
  moonrise: "10:03 PM",
  moonset: "09:20 AM",
  rashi: "मीन",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-03": {
  tithi: "श्रावण कृष्ण षष्ठी",
  nakshatra: "रेवती",
  yog: "धृति",
  karan: "कौलव",
  rahuKaal: "07:27 AM - 09:09 AM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:46 AM",
  sunset: "07:06 PM",
  moonrise: "10:52 PM",
  moonset: "10:13 AM",
  rashi: "मीन",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-04": {
  tithi: "श्रावण कृष्ण सप्तमी",
  nakshatra: "अश्विनी",
  yog: "शूल",
  karan: "तैतिल",
  rahuKaal: "03:45 PM - 05:27 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:47 AM",
  sunset: "07:05 PM",
  moonrise: "11:41 PM",
  moonset: "11:05 AM",
  rashi: "मेष",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-05": {
  tithi: "श्रावण कृष्ण अष्टमी",
  nakshatra: "भरणी",
  yog: "गंड",
  karan: "गर",
  rahuKaal: "12:21 PM - 02:03 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:48 AM",
  sunset: "07:05 PM",
  moonrise: "--",
  moonset: "11:54 AM",
  rashi: "मेष",
  fast: ["कालाष्टमी", "मासिक दुर्गाष्टमी"],
  festival: "कालाष्टमी",
  governmentHoliday: ""
},

"2026-08-06": {
  tithi: "श्रावण कृष्ण नवमी",
  nakshatra: "कृत्तिका",
  yog: "वृद्धि",
  karan: "वणिज",
  rahuKaal: "01:42 PM - 03:24 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:48 AM",
  sunset: "07:04 PM",
  moonrise: "12:30 AM",
  moonset: "12:43 PM",
  rashi: "वृषभ",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-07": {
  tithi: "श्रावण कृष्ण दशमी",
  nakshatra: "रोहिणी",
  yog: "ध्रुव",
  karan: "बव",
  rahuKaal: "10:38 AM - 12:20 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:49 AM",
  sunset: "07:03 PM",
  moonrise: "01:18 AM",
  moonset: "01:31 PM",
  rashi: "वृषभ",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-08": {
  tithi: "श्रावण कृष्ण एकादशी",
  nakshatra: "मृगशिरा",
  yog: "व्याघात",
  karan: "कौलव",
  rahuKaal: "09:00 AM - 10:41 AM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:49 AM",
  sunset: "07:02 PM",
  moonrise: "02:05 AM",
  moonset: "02:18 PM",
  rashi: "मिथुन",
  fast: ["कामिका एकादशी व्रत"],
  festival: "कामिका एकादशी",
  governmentHoliday: ""
},

"2026-08-09": {
  tithi: "श्रावण कृष्ण द्वादशी",
  nakshatra: "आर्द्रा",
  yog: "हर्षण",
  karan: "तैतिल",
  rahuKaal: "05:21 PM - 07:02 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:50 AM",
  sunset: "07:02 PM",
  moonrise: "02:51 AM",
  moonset: "03:04 PM",
  rashi: "मिथुन",
  fast: ["व्रत पारण"],
  festival: "कामिका एकादशी पारण",
  governmentHoliday: ""
},

"2026-08-10": {
  tithi: "श्रावण कृष्ण त्रयोदशी",
  nakshatra: "पुनर्वसु",
  yog: "वज्र",
  karan: "गर",
  rahuKaal: "07:31 AM - 09:12 AM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:51 AM",
  sunset: "07:01 PM",
  moonrise: "03:36 AM",
  moonset: "03:51 PM",
  rashi: "कर्क",
  fast: [],
  festival: "प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-08-11": {
  tithi: "श्रावण कृष्ण चतुर्दशी",
  nakshatra: "पुष्य",
  yog: "सिद्धि",
  karan: "वणिज",
  rahuKaal: "03:42 PM - 05:22 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:51 AM",
  sunset: "07:00 PM",
  moonrise: "04:21 AM",
  moonset: "04:39 PM",
  rashi: "कर्क",
  fast: ["मासिक शिवरात्रि"],
  festival: "मासिक शिवरात्रि",
  governmentHoliday: ""
},

"2026-08-12": {
  tithi: "श्रावण अमावस्या",
  nakshatra: "आश्लेषा",
  yog: "व्यतीपात",
  karan: "विष्टि",
  rahuKaal: "12:21 PM - 02:01 PM",
  abhijit: "12:00 PM - 12:54 PM",
  dosh: "भद्रा / अमावस्या",
  sunrise: "05:52 AM",
  sunset: "06:59 PM",
  moonrise: "05:07 AM",
  moonset: "05:28 PM",
  rashi: "कर्क",
  fast: ["श्रावण अमावस्या व्रत", "हर्याली अमावस्या"],
  festival: "श्रावण अमावस्या, हरियाली अमावस्या",
  governmentHoliday: ""
},

"2026-08-13": {
  tithi: "श्रावण शुक्ल प्रतिपदा",
  nakshatra: "मघा",
  yog: "वरीयान",
  karan: "किंस्तुघ्न",
  rahuKaal: "01:41 PM - 03:21 PM",
  abhijit: "12:00 PM - 12:53 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:52 AM",
  sunset: "06:58 PM",
  moonrise: "05:54 AM",
  moonset: "06:20 PM",
  rashi: "सिंह",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-14": {
  tithi: "श्रावण शुक्ल द्वितीया",
  nakshatra: "पूर्वा फाल्गुनी",
  yog: "परिघ",
  karan: "बालव",
  rahuKaal: "10:40 AM - 12:20 PM",
  abhijit: "12:00 PM - 12:53 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:53 AM",
  sunset: "06:57 PM",
  moonrise: "06:44 AM",
  moonset: "07:13 PM",
  rashi: "सिंह",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-15": {
  tithi: "श्रावण शुक्ल तृतीया",
  nakshatra: "उत्तरा फाल्गुनी",
  yog: "शिव",
  karan: "तैतिल",
  rahuKaal: "09:00 AM - 10:40 AM",
  abhijit: "12:00 PM - 12:53 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:54 AM",
  sunset: "06:56 PM",
  moonrise: "07:37 AM",
  moonset: "08:10 PM",
  rashi: "कन्या",
  fast: ["हरियाली तीज व्रत", "मधुश्रवा"],
  festival: "हरियाली तीज, स्वतंत्रता दिवस",
  governmentHoliday: "स्वतंत्रता दिवस"
},


"2026-08-16": {
  tithi: "श्रावण शुक्ल चतुर्थी",
  nakshatra: "हस्त",
  yog: "सिद्ध",
  karan: "वणिज",
  rahuKaal: "05:16 PM - 06:55 PM",
  abhijit: "12:00 PM - 12:53 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:54 AM",
  sunset: "06:55 PM",
  moonrise: "08:31 AM",
  moonset: "09:07 PM",
  rashi: "कन्या",
  fast: ["विनायक चतुर्थी व्रत"],
  festival: "विनायक चतुर्थी",
  governmentHoliday: ""
},

"2026-08-17": {
  tithi: "श्रावण शुक्ल पञ्चमी",
  nakshatra: "चित्रा",
  yog: "साध्य",
  karan: "बव",
  rahuKaal: "07:33 AM - 09:12 AM",
  abhijit: "12:00 PM - 12:53 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:55 AM",
  sunset: "06:54 PM",
  moonrise: "09:27 AM",
  moonset: "10:07 PM",
  rashi: "तुला",
  fast: ["नाग पंचमी व्रत"],
  festival: "नाग पंचमी",
  governmentHoliday: ""
},

"2026-08-18": {
  tithi: "श्रावण शुक्ल षष्ठी",
  nakshatra: "स्वाती",
  yog: "शुभ",
  karan: "कौलव",
  rahuKaal: "03:37 PM - 05:16 PM",
  abhijit: "11:59 AM - 12:53 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:55 AM",
  sunset: "06:53 PM",
  moonrise: "10:24 AM",
  moonset: "11:07 PM",
  rashi: "तुला",
  fast: [],
  festival: "स्कंद षष्ठी",
  governmentHoliday: ""
},

"2026-08-19": {
  tithi: "श्रावण शुक्ल सप्तमी",
  nakshatra: "विशाखा",
  yog: "शुक्ल",
  karan: "तैतिल",
  rahuKaal: "12:20 PM - 01:59 PM",
  abhijit: "11:59 AM - 12:53 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:56 AM",
  sunset: "06:52 PM",
  moonrise: "11:21 AM",
  moonset: "--",
  rashi: "वृश्चिक",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-20": {
  tithi: "श्रावण शुक्ल अष्टमी",
  nakshatra: "अनुराधा",
  yog: "ब्रह्म",
  karan: "गर",
  rahuKaal: "01:59 PM - 03:37 PM",
  abhijit: "11:59 AM - 12:52 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:57 AM",
  sunset: "06:51 PM",
  moonrise: "12:18 PM",
  moonset: "12:08 AM",
  rashi: "वृश्चिक",
  fast: ["मासिक दुर्गाष्टमी"],
  festival: "दुर्गा अष्टमी",
  governmentHoliday: ""
},

"2026-08-21": {
  tithi: "श्रावण शुक्ल नवमी",
  nakshatra: "ज्येष्ठा",
  yog: "इन्द्र",
  karan: "वणिज",
  rahuKaal: "10:42 AM - 12:20 PM",
  abhijit: "11:59 AM - 12:52 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:57 AM",
  sunset: "06:50 PM",
  moonrise: "01:13 PM",
  moonset: "1:08 AM",
  rashi: "वृश्चिक",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-22": {
  tithi: "श्रावण शुक्ल दशमी",
  nakshatra: "मूल",
  yog: "वैधृति",
  karan: "बव",
  rahuKaal: "09:03 AM - 10:42 AM",
  abhijit: "11:58 AM - 12:52 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:58 AM",
  sunset: "06:49 PM",
  moonrise: "02:07 PM",
  moonset: "02:07 AM",
  rashi: "धनु",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-23": {
  tithi: "श्रावण शुक्ल एकादशी",
  nakshatra: "पूर्वाषाढ़ा",
  yog: "विष्कम्भ",
  karan: "कौलव",
  rahuKaal: "05:11 PM - 06:48 PM",
  abhijit: "11:58 AM - 12:52 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:58 AM",
  sunset: "06:48 PM",
  moonrise: "02:59 PM",
  moonset: "03:04 AM",
  rashi: "धनु",
  fast: ["पुत्रदा एकादशी व्रत"],
  festival: "श्रावण पुत्रदा एकादशी",
  governmentHoliday: ""
},

"2026-08-24": {
  tithi: "श्रावण शुक्ल द्वादशी",
  nakshatra: "उत्तराषाढ़ा",
  yog: "प्रीति",
  karan: "तैतिल",
  rahuKaal: "07:35 AM - 09:14 AM",
  abhijit: "11:58 AM - 12:51 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "05:59 AM",
  sunset: "06:47 PM",
  moonrise: "03:49 PM",
  moonset: "04:00 AM",
  rashi: "मकर",
  fast: ["व्रत पारण"],
  festival: "पुत्रदा एकादशी पारण",
  governmentHoliday: ""
},

"2026-08-25": {
  tithi: "श्रावण शुक्ल त्रयोदशी",
  nakshatra: "श्रवण",
  yog: "आयुष्मान",
  karan: "गर",
  rahuKaal: "03:32 PM - 05:11 PM",
  abhijit: "11:58 AM - 12:51 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:00 AM",
  sunset: "06:46 PM",
  moonrise: "04:36 PM",
  moonset: "04:54 AM",
  rashi: "मकर",
  fast: ["प्रदोष व्रत"],
  festival: "प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-08-26": {
  tithi: "श्रावण शुक्ल चतुर्दशी",
  nakshatra: "धनिष्ठा",
  yog: "सौभाग्य",
  karan: "वणिज",
  rahuKaal: "12:19 PM - 01:58 PM",
  abhijit: "11:57 AM - 12:51 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:00 AM",
  sunset: "06:45 PM",
  moonrise: "05:22 PM",
  moonset: "05:46 AM",
  rashi: "कुंभ",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-27": {
  tithi: "श्रावण पूर्णिमा",
  nakshatra: "शतभिषा",
  yog: "शोभन",
  karan: "विष्टि",
  rahuKaal: "01:57 PM - 03:36 PM",
  abhijit: "11:57 AM - 12:51 PM",
  dosh: "भद्रा / पूर्णिमा",
  sunrise: "06:01 AM",
  sunset: "06:44 PM",
  moonrise: "06:05 PM",
  moonset: "06:37 AM",
  rashi: "कुंभ",
  fast: ["रक्षा बंधन व्रत", "उपाकर्म"],
  festival: "रक्षा बंधन, राखी, संन्यासी पूर्णिमा",
  governmentHoliday: "रक्षा बंधन"
},

"2026-08-28": {
  tithi: "भाद्रपद कृष्ण प्रतिपदा",
  nakshatra: "पूर्वाभाद्रपद",
  yog: "अतिगंड",
  karan: "बव",
  rahuKaal: "10:41 AM - 12:19 PM",
  abhijit: "11:57 AM - 12:50 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:01 AM",
  sunset: "06:43 PM",
  moonrise: "06:48 PM",
  moonset: "07:27 AM",
  rashi: "मीन",
  fast: [],
  festival: "भाद्रपद मास प्रारंभ",
  governmentHoliday: ""
},

"2026-08-29": {
  tithi: "भाद्रपद कृष्ण द्वितीया",
  nakshatra: "उत्तराभाद्रपद",
  yog: "सुकर्मा",
  karan: "कौलव",
  rahuKaal: "09:03 AM - 10:41 AM",
  abhijit: "11:57 AM - 12:50 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:02 AM",
  sunset: "06:42 PM",
  moonrise: "07:31 PM",
  moonset: "08:18 AM",
  rashi: "मीन",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-08-30": {
  tithi: "भाद्रपद कृष्ण तृतीया",
  nakshatra: "रेवती",
  yog: "धृति",
  karan: "तैतिल",
  rahuKaal: "05:05 PM - 06:41 PM",
  abhijit: "11:56 AM - 12:50 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:03 AM",
  sunset: "06:41 PM",
  moonrise: "08:15 PM",
  moonset: "09:10 AM",
  rashi: "मेष",
  fast: ["कजरी तीज व्रत", "बहुला चौथ"],
  festival: "कजरी तीज, बड़ी सात",
  governmentHoliday: ""
},


"2026-09-01": {
  tithi: "भाद्रपद कृष्ण चतुर्थी",
  nakshatra: "अश्विनी",
  yog: "शूल",
  karan: "गर",
  rahuKaal: "03:30 PM - 05:04 PM",
  abhijit: "11:56 AM - 12:49 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:03 AM",
  sunset: "06:40 PM",
  moonrise: "08:59 PM",
  moonset: "10:02 AM",
  rashi: "मेष",
  fast: ["संकष्टी चतुर्थी व्रत"],
  festival: "संकष्टी गणेश चतुर्थी",
  governmentHoliday: ""
},

"2026-09-02": {
  tithi: "भाद्रपद कृष्ण पञ्चमी",
  nakshatra: "भरणी",
  yog: "गंड",
  karan: "वणिज",
  rahuKaal: "12:21 PM - 01:55 PM",
  abhijit: "11:56 AM - 12:49 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:04 AM",
  sunset: "06:39 PM",
  moonrise: "09:46 PM",
  moonset: "10:55 AM",
  rashi: "मेष",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-09-03": {
  tithi: "भाद्रपद कृष्ण षष्ठी",
  nakshatra: "कृत्तिका",
  yog: "वृद्धि",
  karan: "बव",
  rahuKaal: "01:55 PM - 03:29 PM",
  abhijit: "11:55 AM - 12:49 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:04 AM",
  sunset: "06:37 PM",
  moonrise: "10:35 PM",
  moonset: "11:48 AM",
  rashi: "वृषभ",
  fast: [],
  festival: "हलषष्ठी, उभोई",
  governmentHoliday: ""
},

"2026-09-04": {
  tithi: "भाद्रपद कृष्ण सप्तमी",
  nakshatra: "रोहिणी",
  yog: "ध्रुव",
  karan: "कौलव",
  rahuKaal: "10:41 AM - 12:15 PM",
  abhijit: "11:55 AM - 12:48 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:05 AM",
  sunset: "06:36 PM",
  moonrise: "11:26 PM",
  moonset: "12:41 PM",
  rashi: "वृषभ",
  fast: [],
  festival: "श्री कृष्ण जन्माष्टमी (इस्कॉन / वैष्णव)",
  governmentHoliday: ""
},

"2026-09-05": {
  tithi: "भाद्रपद कृष्ण अष्टमी",
  nakshatra: "मृगशिरा",
  yog: "व्याघात",
  karan: "तैतिल",
  rahuKaal: "09:03 AM - 10:41 AM",
  abhijit: "11:55 AM - 12:48 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:05 AM",
  sunset: "06:35 PM",
  moonrise: "--",
  moonset: "01:32 PM",
  rashi: "मिथुन",
  fast: ["श्री कृष्ण जन्माष्टमी व्रत"],
  festival: "श्री कृष्ण जन्माष्टमी",
  governmentHoliday: ""
},

"2026-09-06": {
  tithi: "भाद्रपद कृष्ण नवमी",
  nakshatra: "आर्द्रा",
  yog: "हर्षण",
  karan: "गर",
  rahuKaal: "04:59 PM - 06:34 PM",
  abhijit: "11:55 AM - 12:48 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:06 AM",
  sunset: "06:34 PM",
  moonrise: "12:20 AM",
  moonset: "02:22 PM",
  rashi: "मिथुन",
  fast: ["दही हांडी"],
  festival: "दही हांडी, जन्माष्टमी पारण",
  governmentHoliday: ""
},

"2026-09-07": {
  tithi: "भाद्रपद कृष्ण दशमी",
  nakshatra: "पुनर्वसु",
  yog: "वज्र",
  karan: "वणिज",
  rahuKaal: "07:37 AM - 09:15 AM",
  abhijit: "11:54 AM - 12:47 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:06 AM",
  sunset: "06:33 PM",
  moonrise: "01:15 AM",
  moonset: "03:10 PM",
  rashi: "कर्क",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-09-08": {
  tithi: "भाद्रपद कृष्ण एकादशी",
  nakshatra: "पुष्य",
  yog: "सिद्धि",
  karan: "बव",
  rahuKaal: "03:26 PM - 05:01 PM",
  abhijit: "11:54 AM - 12:47 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:07 AM",
  sunset: "06:32 PM",
  moonrise: "02:11 AM",
  moonset: "03:57 PM",
  rashi: "कर्क",
  fast: ["अजा एकादशी व्रत"],
  festival: "अजा एकादशी",
  governmentHoliday: ""
},

"2026-09-09": {
  tithi: "भाद्रपद कृष्ण द्वादशी",
  nakshatra: "आश्लेषा",
  yog: "व्यतीपात",
  karan: "कौलव",
  rahuKaal: "12:19 PM - 11:54 PM",
  abhijit: "11:54 AM - 12:47 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:07 AM",
  sunset: "06:31 PM",
  moonrise: "03:09 AM",
  moonset: "04:42 PM",
  rashi: "कर्क",
  fast: ["व्रत पारण"],
  festival: "अजा एकादशी पारण",
  governmentHoliday: ""
},

"2026-09-10": {
  tithi: "भाद्रपद कृष्ण त्रयोदशी",
  nakshatra: "मघा",
  yog: "वरीयान",
  karan: "तैतिल",
  rahuKaal: "01:53 PM - 03:28 PM",
  abhijit: "11:53 AM - 12:46 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:08 AM",
  sunset: "06:29 PM",
  moonrise: "04:09 AM",
  moonset: "05:27 PM",
  rashi: "सिंह",
  fast: ["प्रदोष व्रत"],
  festival: "प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-09-11": {
  tithi: "भाद्रपद कृष्ण चतुर्दशी",
  nakshatra: "पूर्वा फाल्गुनी",
  yog: "परिघ",
  karan: "गर",
  rahuKaal: "10:41 AM - 12:19 PM",
  abhijit: "11:53 AM - 12:46 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:08 AM",
  sunset: "06:28 PM",
  moonrise: "05:10 AM",
  moonset: "06:12 PM",
  rashi: "सिंह",
  fast: ["मासिक शिवरात्रि"],
  festival: "मासिक शिवरात्रि",
  governmentHoliday: ""
},

"2026-09-12": {
  tithi: "भाद्रपद अमावस्या",
  nakshatra: "उत्तरा फाल्गुनी",
  yog: "शिव",
  karan: "विष्टि",
  rahuKaal: "09:03 AM - 10:41 AM",
  abhijit: "11:53 AM - 12:46 PM",
  dosh: "भद्रा / अमावस्या",
  sunrise: "06:09 AM",
  sunset: "06:27 PM",
  moonrise: "06:12 AM",
  moonset: "06:58 PM",
  rashi: "कन्या",
  fast: ["भाद्रपद अमावस्या व्रत", "पिठोरी अमावस्या"],
  festival: "भाद्रपद अमावस्या, पोला",
  governmentHoliday: ""
},

"2026-09-13": {
  tithi: "भाद्रपद शुक्ल प्रतिपदा",
  nakshatra: "हस्त",
  yog: "सिद्ध",
  karan: "किंस्तुघ्न",
  rahuKaal: "04:54 PM - 06:26 PM",
  abhijit: "11:52 AM - 12:45 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:09 AM",
  sunset: "06:26 PM",
  moonrise: "07:15 AM",
  moonset: "07:46 PM",
  rashi: "कन्या",
  fast: [],
  festival: "चंद्रदर्शन",
  governmentHoliday: ""
},

"2026-09-14": {
  tithi: "भाद्रपद शुक्ल द्वितीया",
  nakshatra: "चित्रा",
  yog: "साध्य",
  karan: "बालव",
  rahuKaal: "07:38 AM - 09:16 AM",
  abhijit: "11:52 AM - 12:45 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:10 AM",
  sunset: "06:25 PM",
  moonrise: "08:18 AM",
  moonset: "08:35 PM",
  rashi: "तुला",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-09-15": {
  tithi: "भाद्रपद शुक्ल तृतीया",
  nakshatra: "स्वाती",
  yog: "शुभ",
  karan: "कौलव",
  rahuKaal: "03:22 PM - 04:53 PM",
  abhijit: "11:52 AM - 12:45 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:10 AM",
  sunset: "06:24 PM",
  moonrise: "09:20 AM",
  moonset: "09:27 PM",
  rashi: "तुला",
  fast: ["हरतालिका तीज व्रत"],
  festival: "हरतालिका तीज",
  governmentHoliday: ""
},


"2026-09-16": {
  tithi: "भाद्रपद शुक्ल चतुर्थी",
  nakshatra: "विशाखा",
  yog: "शुक्ल",
  karan: "वणिज",
  rahuKaal: "12:18 PM - 01:50 PM",
  abhijit: "11:51 AM - 12:44 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:11 AM",
  sunset: "06:22 PM",
  moonrise: "10:19 AM",
  moonset: "10:20 PM",
  rashi: "वृश्चिक",
  fast: ["गणेश चतुर्थी व्रत"],
  festival: "गणेश चतुर्थी, गणेश उत्सव प्रारंभ",
  governmentHoliday: ""
},

"2026-09-17": {
  tithi: "भाद्रपद शुक्ल पञ्चमी",
  nakshatra: "अनुराधा",
  yog: "ब्रह्म",
  karan: "बव",
  rahuKaal: "01:50 PM - 03:21 PM",
  abhijit: "11:51 AM - 12:44 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:11 AM",
  sunset: "06:21 PM",
  moonrise: "11:15 AM",
  moonset: "11:16 PM",
  rashi: "वृश्चिक",
  fast: ["ऋषि पंचमी व्रत"],
  festival: "ऋषि पंचमी",
  governmentHoliday: ""
},

"2026-09-18": {
  tithi: "भाद्रपद शुक्ल षष्ठी",
  nakshatra: "ज्येष्ठा",
  yog: "इन्द्र",
  karan: "कौलव",
  rahuKaal: "10:41 AM - 12:12 PM",
  abhijit: "11:51 AM - 12:44 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:12 AM",
  sunset: "06:20 PM",
  moonrise: "12:07 PM",
  moonset: "--",
  rashi: "वृश्चिक",
  fast: [],
  festival: "ललई षष्ठी, सूर्य षष्ठी",
  governmentHoliday: ""
},

"2026-09-19": {
  tithi: "भाद्रपद शुक्ल सप्तमी",
  nakshatra: "मूल",
  yog: "वैधृति",
  karan: "तैतिल",
  rahuKaal: "09:03 AM - 10:41 AM",
  abhijit: "11:50 AM - 12:43 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:12 AM",
  sunset: "06:19 PM",
  moonrise: "12:56 PM",
  moonset: "12:14 AM",
  rashi: "धनु",
  fast: ["महाळसा सप्तमी"],
  festival: "संतान सप्तमी",
  governmentHoliday: ""
},

"2026-09-20": {
  tithi: "भाद्रपद शुक्ल अष्टमी",
  nakshatra: "पूर्वाषाढ़ा",
  yog: "विष्कम्भ",
  karan: "गर",
  rahuKaal: "04:47 PM - 06:18 PM",
  abhijit: "11:50 AM - 12:43 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:13 AM",
  sunset: "06:18 PM",
  moonrise: "01:42 PM",
  moonset: "01:13 AM",
  rashi: "धनु",
  fast: ["मासिक दुर्गाष्टमी", "राधा अष्टमी व्रत"],
  festival: "राधा अष्टमी, महालक्ष्मी व्रत प्रारंभ",
  governmentHoliday: ""
},

"2026-09-21": {
  tithi: "भाद्रपद शुक्ल नवमी",
  nakshatra: "उत्तराषाढ़ा",
  yog: "प्रीति",
  karan: "वणिज",
  rahuKaal: "07:39 AM - 09:18 AM",
  abhijit: "11:50 AM - 12:43 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:13 AM",
  sunset: "06:17 PM",
  moonrise: "02:25 PM",
  moonset: "02:14 AM",
  rashi: "मकर",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-09-22": {
  tithi: "भाद्रपद शुक्ल दशमी",
  nakshatra: "श्रवण",
  yog: "आयुष्मान",
  karan: "बव",
  rahuKaal: "03:17 PM - 04:46 PM",
  abhijit: "11:49 AM - 12:42 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:14 AM",
  sunset: "06:15 PM",
  moonrise: "03:07 PM",
  moonset: "03:15 AM",
  rashi: "मकर",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-09-23": {
  tithi: "भाद्रपद शुक्ल एकादशी",
  nakshatra: "धनिष्ठा",
  yog: "सौभाग्य",
  karan: "कौलव",
  rahuKaal: "12:16 PM - 12:49 PM",
  abhijit: "11:49 AM - 12:42 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:14 AM",
  sunset: "06:14 PM",
  moonrise: "03:47 PM",
  moonset: "04:18 AM",
  rashi: "कुंभ",
  fast: ["परिवर्तिनी एकादशी व्रत"],
  festival: "परिवर्तिनी एकादशी (वामन एकादशी)",
  governmentHoliday: ""
},

"2026-09-24": {
  tithi: "भाद्रपद शुक्ल द्वादशी",
  nakshatra: "शतभिषा",
  yog: "शोभन",
  karan: "तैतिल",
  rahuKaal: "01:46 PM - 03:14 PM",
  abhijit: "11:49 AM - 12:42 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:15 AM",
  sunset: "06:13 PM",
  moonrise: "04:26 PM",
  moonset: "05:22 AM",
  rashi: "कुंभ",
  fast: ["व्रत पारण", "वामन जयन्ती"],
  festival: "परिवर्तिनी एकादशी पारण, प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-09-25": {
  tithi: "भाद्रपद शुक्ल त्रयोदशी",
  nakshatra: "पूर्वाभाद्रपद",
  yog: "अतिगंड",
  karan: "गर",
  rahuKaal: "10:41 AM - 12:15 PM",
  abhijit: "11:48 AM - 12:41 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:15 AM",
  sunset: "06:12 PM",
  moonrise: "05:07 PM",
  moonset: "06:27 AM",
  rashi: "मीन",
  fast: [],
  festival: "अनंत चतुर्दशी, गणेश विसर्जन",
  governmentHoliday: ""
},

"2026-09-26": {
  tithi: "भाद्रपद शुक्ल चतुर्दशी",
  nakshatra: "उत्तराभाद्रपद",
  yog: "सुकर्मा",
  karan: "वणिज",
  rahuKaal: "09:03 AM - 10:41 AM",
  abhijit: "11:48 AM - 12:41 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:16 AM",
  sunset: "06:10 PM",
  moonrise: "05:49 PM",
  moonset: "07:33 AM",
  rashi: "मीन",
  fast: [],
  festival: "गणेश विसर्जन",
  governmentHoliday: ""
},

"2026-09-27": {
  tithi: "भाद्रपद पूर्णिमा",
  nakshatra: "रेवती",
  yog: "धृति",
  karan: "विष्टि",
  rahuKaal: "04:42 PM - 06:09 PM",
  abhijit: "11:48 AM - 12:41 PM",
  dosh: "पूर्णिमा / भद्रा",
  sunrise: "06:16 AM",
  sunset: "06:09 PM",
  moonrise: "06:33 PM",
  moonset: "08:40 AM",
  rashi: "मेष",
  fast: ["पितृ पक्ष प्रारंभ", "भाद्रपद पूर्णिमा व्रत"],
  festival: "भाद्रपद पूर्णिमा, प्रतिपदा श्राद्ध",
  governmentHoliday: ""
},

"2026-09-28": {
  tithi: "आश्विन कृष्ण प्रतिपदा",
  nakshatra: "अश्विनी",
  yog: "शूल",
  karan: "बव",
  rahuKaal: "07:40 AM - 09:18 AM",
  abhijit: "11:47 AM - 12:40 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:17 AM",
  sunset: "06:08 PM",
  moonrise: "07:20 PM",
  moonset: "09:47 AM",
  rashi: "मेष",
  fast: ["द्वितीया श्राद्ध"],
  festival: "श्राद्ध पक्ष प्रारंभ",
  governmentHoliday: ""
},

"2026-09-29": {
  tithi: "आश्विन कृष्ण द्वितीया",
  nakshatra: "भरणी",
  yog: "गंड",
  karan: "कौलव",
  rahuKaal: "03:13 PM - 04:40 PM",
  abhijit: "11:47 AM - 12:40 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:17 AM",
  sunset: "06:07 PM",
  moonrise: "08:11 PM",
  moonset: "10:54 AM",
  rashi: "मेष",
  fast: ["तृतीया श्राद्ध"],
  festival: "",
  governmentHoliday: ""
},

"2026-09-30": {
  tithi: "आश्विन कृष्ण तृतीया",
  nakshatra: "कृत्तिका",
  yog: "वृद्धि",
  karan: "तैतिल",
  rahuKaal: "12:15 PM - 12:47 PM",
  abhijit: "11:47 AM - 12:39 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:18 AM",
  sunset: "06:05 PM",
  moonrise: "09:05 PM",
  moonset: "11:59 AM",
  rashi: "वृषभ",
  fast: ["चतुर्थी श्राद्ध", "संकष्टी चतुर्थी व्रत"],
  festival: "महासंकोष्ठी चतुर्थी",
  governmentHoliday: ""
},


"2026-10-01": {
  tithi: "आश्विन कृष्ण चतुर्थी",
  nakshatra: "रोहिणी",
  yog: "ध्रुव",
  karan: "गर",
  rahuKaal: "01:43 PM - 03:11 PM",
  abhijit: "11:47 AM - 12:39 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:18 AM",
  sunset: "06:04 PM",
  moonrise: "10:03 PM",
  moonset: "01:00 PM",
  rashi: "वृषभ",
  fast: ["पंचमी श्राद्ध"],
  festival: "",
  governmentHoliday: ""
},

"2026-10-02": {
  tithi: "आश्विन कृष्ण पञ्चमी",
  nakshatra: "मृगशिरा",
  yog: "व्याघात",
  karan: "वणिज",
  rahuKaal: "10:41 AM - 12:14 PM",
  abhijit: "11:46 AM - 12:39 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:19 AM",
  sunset: "06:03 PM",
  moonrise: "11:03 PM",
  moonset: "01:55 PM",
  rashi: "मिथुन",
  fast: ["षष्ठी श्राद्ध"],
  festival: "महात्मा गांधी जयंती",
  governmentHoliday: "महात्मा गांधी जयंती"
},

"2026-10-03": {
  tithi: "आश्विन कृष्ण षष्ठी",
  nakshatra: "आर्द्रा",
  yog: "हर्षण",
  karan: "बव",
  rahuKaal: "09:03 AM - 10:41 AM",
  abhijit: "11:46 AM - 12:38 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:19 AM",
  sunset: "06:02 PM",
  moonrise: "--",
  moonset: "02:44 PM",
  rashi: "मिथुन",
  fast: ["सप्तमी श्राद्ध"],
  festival: "",
  governmentHoliday: ""
},

"2026-10-04": {
  tithi: "आश्विन कृष्ण सप्तमी",
  nakshatra: "पुनर्वसु",
  yog: "वज्र",
  karan: "कौलव",
  rahuKaal: "04:36 PM - 06:01 PM",
  abhijit: "11:46 AM - 12:38 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:20 AM",
  sunset: "06:01 PM",
  moonrise: "12:05 AM",
  moonset: "03:28 PM",
  rashi: "कर्क",
  fast: ["अष्टमी श्राद्ध"],
  festival: "",
  governmentHoliday: ""
},

"2026-10-05": {
  tithi: "आश्विन कृष्ण अष्टमी",
  nakshatra: "पुष्य",
  yog: "सिद्धि",
  karan: "तैतिल",
  rahuKaal: "07:42 AM - 09:20 AM",
  abhijit: "11:45 AM - 12:38 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:20 AM",
  sunset: "05:59 PM",
  moonrise: "1:07 AM",
  moonset: "04:09 PM",
  rashi: "कर्क",
  fast: ["नवमी श्राद्ध", "जीवित्पुत्रिका व्रत (जिउतिया)"],
  festival: "जीवित्पुत्रिका व्रत",
  governmentHoliday: ""
},

"2026-10-06": {
  tithi: "आश्विन कृष्ण नवमी",
  nakshatra: "आश्लेषा",
  yog: "व्यतीपात",
  karan: "गर",
  rahuKaal: "03:09 PM - 04:35 PM",
  abhijit: "11:45 AM - 12:38 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:21 AM",
  sunset: "05:58 PM",
  moonrise: "02:09 AM",
  moonset: "04:47 PM",
  rashi: "कर्क",
  fast: ["दशमी श्राद्ध"],
  festival: "मातामह श्राद्ध",
  governmentHoliday: ""
},

"2026-10-07": {
  tithi: "आश्विन कृष्ण दशमी",
  nakshatra: "मघा",
  yog: "वरीयान",
  karan: "वणिज",
  rahuKaal: "12:13 PM - 12:47 PM",
  abhijit: "11:45 AM - 12:37 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:21 AM",
  sunset: "05:57 PM",
  moonrise: "03:10 AM",
  moonset: "05:24 PM",
  rashi: "सिंह",
  fast: ["एकादशी श्राद्ध"],
  festival: "",
  governmentHoliday: ""
},

"2026-10-08": {
  tithi: "आश्विन कृष्ण एकादशी",
  nakshatra: "पूर्वा फाल्गुनी",
  yog: "परिघ",
  karan: "बव",
  rahuKaal: "01:40 PM - 03:07 PM",
  abhijit: "11:45 AM - 12:37 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:22 AM",
  sunset: "05:56 PM",
  moonrise: "04:10 AM",
  moonset: "06:01 PM",
  rashi: "सिंह",
  fast: ["इंदिरा एकादशी व्रत", "द्वादशी श्राद्ध"],
  festival: "इंदिरा एकादशी",
  governmentHoliday: ""
},

"2026-10-09": {
  tithi: "आश्विन कृष्ण त्रयोदशी",
  nakshatra: "उत्तरा फाल्गुनी",
  yog: "शिव",
  karan: "कौलव",
  rahuKaal: "10:41 AM - 12:13 PM",
  abhijit: "11:44 AM - 12:37 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:22 AM",
  sunset: "05:55 PM",
  moonrise: "05:10 AM",
  moonset: "06:38 PM",
  rashi: "कन्या",
  fast: ["त्रयोदशी श्राद्ध", "प्रदोष व्रत"],
  festival: "प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-10-10": {
  tithi: "आश्विन कृष्ण चतुर्दशी",
  nakshatra: "हस्त",
  yog: "सिद्ध",
  karan: "तैतिल",
  rahuKaal: "09:04 AM - 10:41 AM",
  abhijit: "11:44 AM - 12:37 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:23 AM",
  sunset: "05:54 PM",
  moonrise: "06:08 AM",
  moonset: "07:18 PM",
  rashi: "कन्या",
  fast: ["चतुर्दशी श्राद्ध (मघा श्राद्ध)"],
  festival: "मासिक शिवरात्रि",
  governmentHoliday: ""
},

"2026-10-11": {
  tithi: "आश्विन अमावस्या",
  nakshatra: "चित्रा",
  yog: "साध्य",
  karan: "विष्टि",
  rahuKaal: "04:31 PM - 05:53 PM",
  abhijit: "11:44 AM - 12:36 PM",
  dosh: "भद्रा / अमावस्या",
  sunrise: "06:23 AM",
  sunset: "05:52 PM",
  moonrise: "07:05 AM",
  moonset: "08:00 PM",
  rashi: "तुला",
  fast: ["सर्व पितृ अमावस्या", "पितृ पक्ष समाप्त"],
  festival: "सर्व पितृ अमावस्या, महालया समाप्त",
  governmentHoliday: ""
},

"2026-10-12": {
  tithi: "आश्विन शुक्ल प्रतिपदा",
  nakshatra: "स्वाती",
  yog: "शुभ",
  karan: "किंस्तुघ्न",
  rahuKaal: "07:43 AM - 09:21 AM",
  abhijit: "11:44 AM - 12:36 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:24 AM",
  sunset: "05:51 PM",
  moonrise: "08:00 AM",
  moonset: "08:44 PM",
  rashi: "तुला",
  fast: ["शरदीय नवरात्रि प्रारंभ", "घटस्थापना"],
  festival: "शारदीय नवरात्रि, कलश स्थापना, महाराजा अग्रसेन जयंती",
  governmentHoliday: ""
},

"2026-10-13": {
  tithi: "आश्विन शुक्ल द्वितीया",
  nakshatra: "विशाखा",
  yog: "शुक्ल",
  karan: "बालव",
  rahuKaal: "03:04 PM - 04:30 PM",
  abhijit: "11:44 AM - 12:36 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:24 AM",
  sunset: "05:50 PM",
  moonrise: "08:52 AM",
  moonset: "09:32 PM",
  rashi: "वृश्चिक",
  fast: ["नवरात्रि द्वितीया"],
  festival: "मां ब्रह्मचारिणी पूजा",
  governmentHoliday: ""
},

"2026-10-14": {
  tithi: "आश्विन शुक्ल तृतीया",
  nakshatra: "अनुराधा",
  yog: "ब्रह्म",
  karan: "कौलव",
  rahuKaal: "12:12 PM - 12:44 PM",
  abhijit: "11:43 AM - 12:36 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:25 AM",
  sunset: "05:49 PM",
  moonrise: "09:41 AM",
  moonset: "10:22 PM",
  rashi: "वृश्चिक",
  fast: ["नवरात्रि तृतीया", "सौभाग्य सुंदरी व्रत"],
  festival: "मां चंद्रघंटा पूजा",
  governmentHoliday: ""
},

"2026-10-15": {
  tithi: "आश्विन शुक्ल चतुर्थी",
  nakshatra: "ज्येष्ठा",
  yog: "इन्द्र",
  karan: "तैतिल",
  rahuKaal: "01:37 PM - 03:03 PM",
  abhijit: "11:43 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:25 AM",
  sunset: "05:48 PM",
  moonrise: "10:25 AM",
  moonset: "11:15 PM",
  rashi: "वृश्चिक",
  fast: ["विनायक चतुर्थी व्रत", "नवरात्रि चतुर्थी"],
  festival: "मां कूष्मांडा पूजा",
  governmentHoliday: ""
},


"2026-10-16": {
  tithi: "आश्विन शुक्ल पञ्चमी",
  nakshatra: "मूल",
  yog: "वैधृति",
  karan: "गर",
  rahuKaal: "10:41 AM - 12:12 PM",
  abhijit: "11:43 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:26 AM",
  sunset: "05:47 PM",
  moonrise: "11:06 AM",
  moonset: "--",
  rashi: "धनु",
  fast: ["स्कंद षष्ठी", "नवरात्रि पञ्चमी"],
  festival: "मां स्कंदमाता पूजा, उपांग ललिता व्रत",
  governmentHoliday: ""
},

"2026-10-17": {
  tithi: "आश्विन शुक्ल षष्ठी",
  nakshatra: "पूर्वाषाढ़ा",
  yog: "विष्कम्भ",
  karan: "वणिज",
  rahuKaal: "09:05 AM - 10:41 AM",
  abhijit: "11:43 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:27 AM",
  sunset: "05:46 PM",
  moonrise: "11:43 AM",
  moonset: "12:10 AM",
  rashi: "धनु",
  fast: ["नवरात्रि षष्ठी"],
  festival: "मां कात्यायनी पूजा, सरस्वती आवाहन",
  governmentHoliday: ""
},

"2026-10-18": {
  tithi: "आश्विन शुक्ल सप्तमी",
  nakshatra: "उत्तराषाढ़ा",
  yog: "प्रीति",
  karan: "बव",
  rahuKaal: "04:26 PM - 05:44 PM",
  abhijit: "11:43 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:27 AM",
  sunset: "05:44 PM",
  moonrise: "12:18 PM",
  moonset: "01:06 AM",
  rashi: "मकर",
  fast: ["महा सप्तमी", "नवरात्रि सप्तमी"],
  festival: "मां कालरात्रि पूजा, सरस्वती पूजा",
  governmentHoliday: ""
},

"2026-10-19": {
  tithi: "आश्विन शुक्ल अष्टमी",
  nakshatra: "श्रवण",
  yog: "आयुष्मान",
  karan: "कौलव",
  rahuKaal: "07:45 AM - 09:21 AM",
  abhijit: "11:43 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:28 AM",
  sunset: "05:43 PM",
  moonrise: "12:52 PM",
  moonset: "02:04 AM",
  rashi: "मकर",
  fast: ["महा अष्टमी व्रत", "कन्या पूजन", "दुर्गा महाष्टमी"],
  festival: "मां महागौरी पूजा, दुर्गा महाष्टमी",
  governmentHoliday: "महा अष्टमी / महानवमी"
},

"2026-10-20": {
  tithi: "आश्विन शुक्ल नवमी",
  nakshatra: "धनिष्ठा",
  yog: "सौभाग्य",
  karan: "तैतिल",
  rahuKaal: "02:59 PM - 04:25 PM",
  abhijit: "11:43 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:28 AM",
  sunset: "05:42 PM",
  moonrise: "01:27 PM",
  moonset: "03:03 AM",
  rashi: "कुंभ",
  fast: ["महानवमी", "नवरात्रि पारण"],
  festival: "मां सिद्धिदात्री पूजा, आयुध पूजा, नवमी हवन",
  governmentHoliday: ""
},

"2026-10-21": {
  tithi: "आश्विन शुक्ल दशमी",
  nakshatra: "शतभिषा",
  yog: "शोभन",
  karan: "गर",
  rahuKaal: "12:11 PM - 12:43 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:29 AM",
  sunset: "05:41 PM",
  moonrise: "02:03 PM",
  moonset: "04:02 AM",
  rashi: "कुंभ",
  fast: ["विशाल दशहरा व्रत"],
  festival: "विजयादशमी (दशहरा), रावण दहन, सिमोत्सव",
  governmentHoliday: "विजयादशमी (दशहरा)"
},

"2026-10-22": {
  tithi: "आश्विन शुक्ल एकादशी",
  nakshatra: "पूर्वाभाद्रपद",
  yog: "अतिगंड",
  karan: "वणिज",
  rahuKaal: "01:34 PM - 03:00 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:29 AM",
  sunset: "05:40 PM",
  moonrise: "02:42 PM",
  moonset: "05:03 AM",
  rashi: "मीन",
  fast: ["पापांकुशा एकादशी व्रत"],
  festival: "पापांकुशा एकादशी",
  governmentHoliday: ""
},

"2026-10-23": {
  tithi: "आश्विन शुक्ल द्वादशी",
  nakshatra: "उत्तराभाद्रपद",
  yog: "सुकर्मा",
  karan: "बव",
  rahuKaal: "10:41 AM - 12:11 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:30 AM",
  sunset: "05:39 PM",
  moonrise: "03:24 PM",
  moonset: "06:05 AM",
  rashi: "मीन",
  fast: ["व्रत पारण"],
  festival: "पापांकुशा एकादशी पारण, प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-10-24": {
  tithi: "आश्विन शुक्ल त्रयोदशी",
  nakshatra: "रेवती",
  yog: "धृति",
  karan: "कौलव",
  rahuKaal: "09:06 AM - 10:41 AM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:31 AM",
  sunset: "05:38 PM",
  moonrise: "04:11 PM",
  moonset: "07:08 AM",
  rashi: "मेष",
  fast: ["प्रदोष व्रत"],
  festival: "प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-10-25": {
  tithi: "आश्विन शुक्ल चतुर्दशी",
  nakshatra: "अश्विनी",
  yog: "शूल",
  karan: "तैतिल",
  rahuKaal: "04:22 PM - 05:37 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:31 AM",
  sunset: "05:37 PM",
  moonrise: "05:03 PM",
  moonset: "08:12 AM",
  rashi: "मेष",
  fast: [],
  festival: "कोजागर पूर्णिमा (पूर्णिमा व्रत पूर्व संध्या)",
  governmentHoliday: ""
},

"2026-10-26": {
  tithi: "आश्विन पूर्णिमा",
  nakshatra: "भरणी",
  yog: "गंड",
  karan: "विष्टि",
  rahuKaal: "07:47 AM - 09:22 AM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "पूर्णिमा / भद्रा",
  sunrise: "06:32 AM",
  sunset: "05:36 PM",
  moonrise: "06:00 PM",
  moonset: "09:14 AM",
  rashi: "मेष",
  fast: ["शरद पूर्णिमा व्रत", "कोजागर व्रत"],
  festival: "शरद पूर्णिमा, महर्षि वाल्मीकि जयंती",
  governmentHoliday: ""
},

"2026-10-27": {
  tithi: "कार्तिक कृष्ण प्रतिपदा",
  nakshatra: "कृत्तिका",
  yog: "वृद्धि",
  karan: "बव",
  rahuKaal: "02:56 PM - 04:21 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:32 AM",
  sunset: "05:35 PM",
  moonrise: "07:01 PM",
  moonset: "10:14 AM",
  rashi: "वृषभ",
  fast: [],
  festival: "कार्तिक मास प्रारंभ (उत्तर भारत)",
  governmentHoliday: ""
},

"2026-10-28": {
  tithi: "कार्तिक कृष्ण द्वितीया",
  nakshatra: "रोहिणी",
  yog: "ध्रुव",
  karan: "कौलव",
  rahuKaal: "12:10 PM - 12:42 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:33 AM",
  sunset: "05:34 PM",
  moonrise: "08:04 PM",
  moonset: "11:10 AM",
  rashi: "वृषभ",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-10-29": {
  tithi: "कार्तिक कृष्ण तृतीया",
  nakshatra: "मृगशिरा",
  yog: "व्याघात",
  karan: "तैतिल",
  rahuKaal: "01:29 PM - 02:54 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:34 AM",
  sunset: "05:33 PM",
  moonrise: "09:09 PM",
  moonset: "12:00 PM",
  rashi: "मिथुन",
  fast: ["संकष्टी चतुर्थी व्रत", "करवा चौथ (चंद्रोदय अनुसार)"],
  festival: "करवा चौथ",
  governmentHoliday: ""
},

"2026-10-30": {
  tithi: "कार्तिक कृष्ण चतुर्थी",
  nakshatra: "आर्द्रा",
  yog: "हर्षण",
  karan: "गर",
  rahuKaal: "10:41 AM - 12:10 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:34 AM",
  sunset: "05:32 PM",
  moonrise: "10:14 PM",
  moonset: "12:46 PM",
  rashi: "मिथुन",
  fast: ["संकष्टी गणेश चतुर्थी"],
  festival: "संकष्टी गणेश चतुर्थी",
  governmentHoliday: ""
},

"2026-10-31": {
  tithi: "कार्तिक कृष्ण पञ्चमी",
  nakshatra: "पुनर्वसु",
  yog: "वज्र",
  karan: "वणिज",
  rahuKaal: "09:07 AM - 10:41 AM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:35 AM",
  sunset: "05:31 PM",
  moonrise: "11:18 PM",
  moonset: "01:27 PM",
  rashi: "कर्क",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-11-01": {
  tithi: "कार्तिक कृष्ण षष्ठी",
  nakshatra: "पुष्य",
  yog: "सिद्धि",
  karan: "बव",
  rahuKaal: "04:19 PM - 05:30 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:35 AM",
  sunset: "05:30 PM",
  moonrise: "--",
  moonset: "02:04 PM",
  rashi: "कर्क",
  fast: [],
  festival: "अहोइ अष्टमी व्रत",
  governmentHoliday: ""
},

"2026-11-02": {
  tithi: "कार्तिक कृष्ण सप्तमी",
  nakshatra: "आश्लेषा",
  yog: "व्यतीपात",
  karan: "कौलव",
  rahuKaal: "07:49 AM - 09:23 AM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:36 AM",
  sunset: "05:29 PM",
  moonrise: "12:21 AM",
  moonset: "02:39 PM",
  rashi: "कर्क",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-11-03": {
  tithi: "कार्तिक कृष्ण अष्टमी",
  nakshatra: "मघा",
  yog: "वरीयान",
  karan: "तैतिल",
  rahuKaal: "02:53 PM - 04:18 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:37 AM",
  sunset: "05:28 PM",
  moonrise: "01:23 AM",
  moonset: "03:13 PM",
  rashi: "सिंह",
  fast: ["कालाष्टमी", "मासिक दुर्गाष्टमी"],
  festival: "कालाष्टमी",
  governmentHoliday: ""
},

"2026-11-04": {
  tithi: "कार्तिक कृष्ण नवमी",
  nakshatra: "पूर्वा फाल्गुनी",
  yog: "परिघ",
  karan: "गर",
  rahuKaal: "12:09 PM - 12:42 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:37 AM",
  sunset: "05:28 PM",
  moonrise: "02:24 AM",
  moonset: "03:47 PM",
  rashi: "सिंह",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-11-05": {
  tithi: "कार्तिक कृष्ण दशमी",
  nakshatra: "उत्तरा फाल्गुनी",
  yog: "शिव",
  karan: "वणिज",
  rahuKaal: "01:26 PM - 02:51 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:38 AM",
  sunset: "05:27 PM",
  moonrise: "03:26 AM",
  moonset: "04:22 PM",
  rashi: "कन्या",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-11-06": {
  tithi: "कार्तिक कृष्ण एकादशी",
  nakshatra: "हस्त",
  yog: "सिद्ध",
  karan: "बव",
  rahuKaal: "10:41 AM - 12:09 PM",
  abhijit: "11:42 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:39 AM",
  sunset: "05:26 PM",
  moonrise: "04:28 AM",
  moonset: "04:59 PM",
  rashi: "कन्या",
  fast: ["रमा एकादशी व्रत"],
  festival: "रमा एकादशी",
  governmentHoliday: ""
},

"2026-11-07": {
  tithi: "कार्तिक कृष्ण द्वादशी",
  nakshatra: "चित्रा",
  yog: "साध्य",
  karan: "कौलव",
  rahuKaal: "09:09 AM - 10:41 AM",
  abhijit: "11:43 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:39 AM",
  sunset: "05:25 PM",
  moonrise: "05:29 AM",
  moonset: "05:39 PM",
  rashi: "तुला",
  fast: ["व्रत पारण", "गोदावरी पुष्कर स्नान"],
  festival: "रमा एकादशी पारण, धनतेरस पूर्व संध्या",
  governmentHoliday: ""
},

"2026-11-08": {
  tithi: "कार्तिक कृष्ण त्रयोदशी",
  nakshatra: "स्वाती",
  yog: "शुभ",
  karan: "तैतिल",
  rahuKaal: "04:16 PM - 05:25 PM",
  abhijit: "11:43 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:40 AM",
  sunset: "05:24 PM",
  moonrise: "06:31 AM",
  moonset: "06:22 PM",
  rashi: "तुला",
  fast: ["धनतेरस व्रत", "प्रदोष व्रत", "धन्वंतरि जयन्ती"],
  festival: "धनतेरस, प्रदोष व्रत, यम दीपदान",
  governmentHoliday: ""
},

"2026-11-09": {
  tithi: "कार्तिक कृष्ण चतुर्दशी",
  nakshatra: "विशाखा",
  yog: "शुक्ल",
  karan: "विष्टि",
  rahuKaal: "07:51 AM - 09:24 AM",
  abhijit: "11:43 AM - 12:34 PM",
  dosh: "भद्रा / नरक चतुर्दशी",
  sunrise: "06:41 AM",
  sunset: "05:24 PM",
  moonrise: "07:31 AM",
  moonset: "07:11 PM",
  rashi: "वृश्चिक",
  fast: ["नरक चतुर्दशी", "छोटी दीपावली", "मासिक शिवरात्रि"],
  festival: "नरक चतुर्दशी, हनुमान पूजा, रूप चतुर्दशी",
  governmentHoliday: ""
},

"2026-11-10": {
  tithi: "कार्तिक अमावस्या",
  nakshatra: "अनुराधा",
  yog: "ब्रह्म",
  karan: "चतुष्पाद",
  rahuKaal: "02:50 PM - 04:16 PM",
  abhijit: "11:43 AM - 12:34 PM",
  dosh: "अमावस्या",
  sunrise: "06:41 AM",
  sunset: "05:23 PM",
  moonrise: "08:30 AM",
  moonset: "08:05 PM",
  rashi: "वृश्चिक",
  fast: ["दीपावली व्रत", "लक्ष्मी पूजा", "कार्तिक अमावस्या"],
  festival: "दीपावली (दिवाली), लक्ष्मी-गणेश पूजन",
  governmentHoliday: "दीपावली (दिवाली)"
},

"2026-11-11": {
  tithi: "कार्तिक शुक्ल प्रतिपदा",
  nakshatra: "ज्येष्ठा",
  yog: "इन्द्र",
  karan: "किंस्तुघ्न",
  rahuKaal: "12:09 PM - 12:42 PM",
  abhijit: "11:43 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:42 AM",
  sunset: "05:22 PM",
  moonrise: "09:27 AM",
  moonset: "09:03 PM",
  rashi: "वृश्चिक",
  fast: ["गोवर्धन पूजा", "अन्नकूट"],
  festival: "गोवर्धन पूजा, बलि प्रतिपदा",
  governmentHoliday: "गोवर्धन पूजा"
},

"2026-11-12": {
  tithi: "कार्तिक शुक्ल द्वितीया",
  nakshatra: "मूल",
  yog: "वैधृति",
  karan: "बालव",
  rahuKaal: "01:24 PM - 02:50 PM",
  abhijit: "11:43 AM - 12:34 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:43 AM",
  sunset: "05:22 PM",
  moonrise: "10:20 AM",
  moonset: "10:04 PM",
  rashi: "धनु",
  fast: ["भैया दूज", "यम द्वितीया"],
  festival: "भाइजीव, भाई दूज",
  governmentHoliday: "भाई दूज"
},

"2026-11-13": {
  tithi: "कार्तिक शुक्ल तृतीया",
  nakshatra: "पूर्वाषाढ़ा",
  yog: "विष्कम्भ",
  karan: "कौलव",
  rahuKaal: "10:42 AM - 12:09 PM",
  abhijit: "11:44 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:43 AM",
  sunset: "05:21 PM",
  moonrise: "11:09 AM",
  moonset: "11:06 PM",
  rashi: "धनु",
  fast: ["विनायक चतुर्थी व्रत", "सौभाग्य सुंदरी व्रत"],
  festival: "विनायक चतुर्थी",
  governmentHoliday: ""
},

"2026-11-14": {
  tithi: "कार्तिक शुक्ल चतुर्थी",
  nakshatra: "उत्तराषाढ़ा",
  yog: "प्रीति",
  karan: "तैतिल",
  rahuKaal: "09:11 AM - 10:42 AM",
  abhijit: "11:44 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:44 AM",
  sunset: "05:20 PM",
  moonrise: "11:55 AM",
  moonset: "--",
  rashi: "मकर",
  fast: ["लाभ पंचमी (अगले दिन)"],
  festival: "बाल दिवस, छठ पूजा (नहाय-खाय)",
  governmentHoliday: ""
},

"2026-11-15": {
  tithi: "कार्तिक शुक्ल पंचमी",
  nakshatra: "श्रवण",
  yog: "आयुष्मान",
  karan: "गर",
  rahuKaal: "04:14 PM - 05:20 PM",
  abhijit: "11:44 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:45 AM",
  sunset: "05:20 PM",
  moonrise: "12:36 PM",
  moonset: "12:10 AM",
  rashi: "मकर",
  fast: ["छठ पूजा (खरना)"],
  festival: "छठ पूजा खरना (लोहंडा)",
  governmentHoliday: ""
},

"2026-11-16": {
  tithi: "कार्तिक शुक्ल षष्ठी",
  nakshatra: "धनिष्ठा",
  yog: "सौभाग्य",
  karan: "वणिज",
  rahuKaal: "07:53 AM - 09:25 AM",
  abhijit: "11:44 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:46 AM",
  sunset: "05:19 PM",
  moonrise: "01:15 PM",
  moonset: "01:15 AM",
  rashi: "कुंभ",
  fast: ["छठ पूजा (संध्या अर्घ्य)"],
  festival: "सूर्य षष्ठी व्रत (छठ पूजा)",
  governmentHoliday: ""
},

"2026-11-17": {
  tithi: "कार्तिक शुक्ल सप्तमी",
  nakshatra: "शतभिषा",
  yog: "शोभन",
  karan: "बव",
  rahuKaal: "02:48 PM - 04:14 PM",
  abhijit: "11:44 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:46 AM",
  sunset: "05:19 PM",
  moonrise: "01:52 PM",
  moonset: "02:20 AM",
  rashi: "कुंभ",
  fast: ["छठ पूजा (उषा अर्घ्य और पारण)"],
  festival: "छठ पूजा समाप्त, सूर्य सप्तमी",
  governmentHoliday: ""
},

"2026-11-18": {
  tithi: "कार्तिक शुक्ल अष्टमी",
  nakshatra: "पूर्वाभाद्रपद",
  yog: "अतिगंड",
  karan: "कौलव",
  rahuKaal: "12:09 PM - 12:35 PM",
  abhijit: "11:45 AM - 12:36 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:47 AM",
  sunset: "05:18 PM",
  moonrise: "02:27 PM",
  moonset: "03:26 AM",
  rashi: "मीन",
  fast: ["गोपाष्टमी व्रत", "दुर्गाष्टमी"],
  festival: "गोपाष्टमी, गोधूलि पूजा",
  governmentHoliday: ""
},

"2026-11-19": {
  tithi: "कार्तिक शुक्ल नवमी",
  nakshatra: "उत्तराभाद्रपद",
  yog: "सुकर्मा",
  karan: "तैतिल",
  rahuKaal: "01:23 PM - 02:48 PM",
  abhijit: "11:45 AM - 12:36 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:48 AM",
  sunset: "05:18 PM",
  moonrise: "03:03 PM",
  moonset: "04:32 AM",
  rashi: "मीन",
  fast: ["अक्षय नवमी", "कूष्मांडा नवमी"],
  festival: "अक्षय नवमी (धात्री नवमी)",
  governmentHoliday: ""
},

"2026-11-20": {
  tithi: "कार्तिक शुक्ल दशमी",
  nakshatra: "रेवती",
  yog: "धृति",
  karan: "गर",
  rahuKaal: "10:44 AM - 12:09 PM",
  abhijit: "11:45 AM - 12:36 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:49 AM",
  sunset: "05:17 PM",
  moonrise: "03:40 PM",
  moonset: "05:39 AM",
  rashi: "मेष",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-11-21": {
  tithi: "कार्तिक शुक्ल एकादशी",
  nakshatra: "अश्विनी",
  yog: "शूल",
  karan: "वणिज",
  rahuKaal: "09:13 AM - 10:44 AM",
  abhijit: "11:46 AM - 12:37 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:49 AM",
  sunset: "05:17 PM",
  moonrise: "04:19 PM",
  moonset: "06:47 AM",
  rashi: "मेष",
  fast: ["प्रबोधनी (देवोत्थान) एकादशी व्रत"],
  festival: "देवउठनी एकादशी, तुलसी विवाह",
  governmentHoliday: ""
},

"2026-11-22": {
  tithi: "कार्तिक शुक्ल द्वादशी",
  nakshatra: "भरणी",
  yog: "गंड",
  karan: "बव",
  rahuKaal: "04:12 PM - 05:17 PM",
  abhijit: "11:46 AM - 12:37 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:50 AM",
  sunset: "05:16 PM",
  moonrise: "05:00 PM",
  moonset: "07:54 AM",
  rashi: "मेष",
  fast: ["व्रत पारण", "प्रदोष व्रत (सायं)"],
  festival: "तुलसी विवाह, चातुर्मास समाप्त",
  governmentHoliday: ""
},

"2026-11-23": {
  tithi: "कार्तिक शुक्ल त्रयोदशी",
  nakshatra: "कृत्तिका",
  yog: "वृद्धि",
  karan: "कौलव",
  rahuKaal: "07:56 AM - 09:27 AM",
  abhijit: "11:46 AM - 12:37 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:51 AM",
  sunset: "05:16 PM",
  moonrise: "05:45 PM",
  moonset: "09:00 AM",
  rashi: "वृषभ",
  fast: ["प्रदोष व्रत"],
  festival: "प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-11-24": {
  tithi: "कार्तिक शुक्ल चतुर्दशी",
  nakshatra: "रोहिणी",
  yog: "ध्रुव",
  karan: "तैतिल",
  rahuKaal: "02:46 PM - 04:12 PM",
  abhijit: "11:47 AM - 12:38 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:52 AM",
  sunset: "05:16 PM",
  moonrise: "06:33 PM",
  moonset: "10:02 AM",
  rashi: "वृषभ",
  fast: ["वैकुण्ठ चतुर्दशी व्रत"],
  festival: "वैकुण्ठ चतुर्दशी, मणिकर्णिका स्नान",
  governmentHoliday: ""
},

"2026-11-25": {
  tithi: "कार्तिक पूर्णिमा",
  nakshatra: "मृगशिरा",
  yog: "व्याघात",
  karan: "विष्टि",
  rahuKaal: "12:09 PM - 12:35 PM",
  abhijit: "11:47 AM - 12:38 PM",
  dosh: "पूर्णिमा / भद्रा",
  sunrise: "06:52 AM",
  sunset: "05:15 PM",
  moonrise: "07:25 PM",
  moonset: "10:59 AM",
  rashi: "मिथुन",
  fast: ["कार्तिक पूर्णिमा व्रत", "देव दीपावली"],
  festival: "कार्तिक पूर्णिमा, देव दीपावली, गुरु नानक जयंती",
  governmentHoliday: "गुरु नानक जयंती / कार्तिक पूर्णिमा"
},

"2026-11-26": {
  tithi: "मार्गशीर्ष कृष्ण प्रतिपदा",
  nakshatra: "आर्द्रा",
  yog: "हर्षण",
  karan: "बव",
  rahuKaal: "01:21 PM - 02:46 PM",
  abhijit: "11:47 AM - 12:38 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:53 AM",
  sunset: "05:15 PM",
  moonrise: "08:21 PM",
  moonset: "11:51 AM",
  rashi: "मिथुन",
  fast: [],
  festival: "मार्गशीर्ष मास प्रारंभ (उत्तर भारत)",
  governmentHoliday: ""
},

"2026-11-27": {
  tithi: "मार्गशीर्ष कृष्ण द्वितीया",
  nakshatra: "पुनर्वसु",
  yog: "वज्र",
  karan: "कौलव",
  rahuKaal: "10:45 AM - 12:09 PM",
  abhijit: "11:48 AM - 12:39 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:54 AM",
  sunset: "05:15 PM",
  moonrise: "09:19 PM",
  moonset: "12:37 PM",
  rashi: "कर्क",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-11-28": {
  tithi: "मार्गशीर्ष कृष्ण तृतीया",
  nakshatra: "पुष्य",
  yog: "सिद्धि",
  karan: "तैतिल",
  rahuKaal: "09:16 AM - 10:45 AM",
  abhijit: "11:48 AM - 12:39 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:55 AM",
  sunset: "05:14 PM",
  moonrise: "10:20 PM",
  moonset: "01:19 PM",
  rashi: "कर्क",
  fast: ["संकष्टी चतुर्थी व्रत"],
  festival: "संकष्टी गणेश चतुर्थी",
  governmentHoliday: ""
},

"2026-11-29": {
  tithi: "मार्गशीर्ष कृष्ण चतुर्थी",
  nakshatra: "आश्लेषा",
  yog: "व्यतीपात",
  karan: "गर",
  rahuKaal: "04:11 PM - 05:14 PM",
  abhijit: "11:49 AM - 12:40 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:55 AM",
  sunset: "05:14 PM",
  moonrise: "11:22 PM",
  moonset: "01:57 PM",
  rashi: "कर्क",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-11-30": {
  tithi: "मार्गशीर्ष कृष्ण पंचमी",
  nakshatra: "मघा",
  yog: "वरीयान",
  karan: "वणिज",
  rahuKaal: "07:58 AM - 09:28 AM",
  abhijit: "11:49 AM - 12:40 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:56 AM",
  sunset: "05:14 PM",
  moonrise: "--",
  moonset: "02:32 PM",
  rashi: "सिंह",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-01": {
  tithi: "मार्गशीर्ष कृष्ण षष्ठी",
  nakshatra: "पुष्य",
  yog: "शिव",
  karan: "तैतिल",
  rahuKaal: "02:51 PM - 04:09 PM",
  abhijit: "11:53 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:56 AM",
  sunset: "05:25 PM",
  moonrise: "09:21 PM",
  moonset: "10:39 AM",
  rashi: "कर्क",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-02": {
  tithi: "मार्गशीर्ष कृष्ण सप्तमी",
  nakshatra: "आश्लेषा",
  yog: "सिद्ध",
  karan: "वणिज",
  rahuKaal: "12:13 PM - 01:32 PM",
  abhijit: "11:54 AM - 12:35 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:57 AM",
  sunset: "05:25 PM",
  moonrise: "10:31 PM",
  moonset: "11:24 AM",
  rashi: "कर्क",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-03": {
  tithi: "मार्गशीर्ष कृष्ण अष्टमी",
  nakshatra: "मघा",
  yog: "साध्य",
  karan: "बव",
  rahuKaal: "01:32 PM - 02:51 PM",
  abhijit: "11:54 AM - 12:36 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:58 AM",
  sunset: "05:25 PM",
  moonrise: "11:42 PM",
  moonset: "12:13 PM",
  rashi: "सिंह",
  fast: ["कालाष्टमी", "मासिक दुर्गाष्टमी"],
  festival: "कालाष्टमी",
  governmentHoliday: ""
},

"2026-12-04": {
  tithi: "मार्गशीर्ष कृष्ण नवमी",
  nakshatra: "पूर्वा फाल्गुनी",
  yog: "शुभ",
  karan: "कौलव",
  rahuKaal: "10:55 AM - 12:13 PM",
  abhijit: "11:55 AM - 12:36 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:59 AM",
  sunset: "05:25 PM",
  moonrise: "--",
  moonset: "01:07 PM",
  rashi: "सिंह",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-05": {
  tithi: "मार्गशीर्ष कृष्ण दशमी",
  nakshatra: "उत्तरा फाल्गुनी",
  yog: "शुक्ल",
  karan: "गर",
  rahuKaal: "09:36 AM - 10:55 AM",
  abhijit: "11:55 AM - 12:36 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "06:59 AM",
  sunset: "05:25 PM",
  moonrise: "12:54 AM",
  moonset: "02:04 PM",
  rashi: "कन्या",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-06": {
  tithi: "मार्गशीर्ष कृष्ण एकादशी",
  nakshatra: "हस्त",
  yog: "ब्रह्म",
  karan: "वणिज",
  rahuKaal: "04:09 PM - 05:25 PM",
  abhijit: "11:56 AM - 12:37 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:00 AM",
  sunset: "05:25 PM",
  moonrise: "02:06 AM",
  moonset: "03:05 PM",
  rashi: "कन्या",
  fast: ["उत्पन्ना एकादशी व्रत"],
  festival: "उत्पन्ना एकादशी",
  governmentHoliday: ""
},

"2026-12-07": {
  tithi: "मार्गशीर्ष कृष्ण द्वादशी",
  nakshatra: "चित्रा",
  yog: "इन्द्र",
  karan: "बव",
  rahuKaal: "08:18 AM - 09:36 AM",
  abhijit: "11:56 AM - 12:37 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:01 AM",
  sunset: "05:25 PM",
  moonrise: "03:19 AM",
  moonset: "04:09 PM",
  rashi: "तुला",
  fast: ["व्रत पारण"],
  festival: "उत्पन्ना एकादशी पारण",
  governmentHoliday: ""
},

"2026-12-08": {
  tithi: "मार्गशीर्ष कृष्ण त्रयोदशी",
  nakshatra: "स्वाती",
  yog: "वैधृति",
  karan: "कौलव",
  rahuKaal: "02:52 PM - 04:09 PM",
  abhijit: "11:57 AM - 12:37 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:01 AM",
  sunset: "05:25 PM",
  moonrise: "04:33 AM",
  moonset: "05:15 PM",
  rashi: "तुला",
  fast: ["प्रदोष व्रत"],
  festival: "प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-12-09": {
  tithi: "मार्गशीर्ष कृष्ण चतुर्दशी",
  nakshatra: "विशाखा",
  yog: "विष्कम्भ",
  karan: "तैतिल",
  rahuKaal: "12:15 PM - 01:33 PM",
  abhijit: "11:57 AM - 12:38 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:02 AM",
  sunset: "05:25 PM",
  moonrise: "05:48 AM",
  moonset: "06:23 PM",
  rashi: "वृश्चिक",
  fast: ["मासिक शिवरात्रि"],
  festival: "मासिक शिवरात्रि",
  governmentHoliday: ""
},

"2026-12-10": {
  tithi: "मार्गशीर्ष अमावस्या",
  nakshatra: "अनुराधा",
  yog: "प्रीति",
  karan: "विष्टि",
  rahuKaal: "01:34 PM - 02:52 PM",
  abhijit: "11:58 AM - 12:38 PM",
  dosh: "अमावस्या / भद्रा",
  sunrise: "07:03 AM",
  sunset: "05:25 PM",
  moonrise: "07:03 AM",
  moonset: "07:31 PM",
  rashi: "वृश्चिक",
  fast: ["मार्गशीर्ष अमावस्या व्रत"],
  festival: "मार्गशीर्ष अमावस्या",
  governmentHoliday: ""
},

"2026-12-11": {
  tithi: "मार्गशीर्ष शुक्ल प्रतिपदा",
  nakshatra: "ज्येष्ठा",
  yog: "आयुष्मान",
  karan: "किंस्तुघ्न",
  rahuKaal: "10:58 AM - 12:15 PM",
  abhijit: "11:58 AM - 12:38 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:03 AM",
  sunset: "05:25 PM",
  moonrise: "08:18 AM",
  moonset: "08:41 PM",
  rashi: "वृश्चिक",
  fast: [],
  festival: "चंद्रदर्शन",
  governmentHoliday: ""
},

"2026-12-12": {
  tithi: "मार्गशीर्ष शुक्ल द्वितीया",
  nakshatra: "मूल",
  yog: "सौभाग्य",
  karan: "बालव",
  rahuKaal: "09:40 AM - 10:58 AM",
  abhijit: "11:59 AM - 12:39 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:04 AM",
  sunset: "05:25 PM",
  moonrise: "09:32 AM",
  moonset: "09:51 PM",
  rashi: "धनु",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-13": {
  tithi: "मार्गशीर्ष शुक्ल तृतीया",
  nakshatra: "पूर्वाषाढ़ा",
  yog: "शोभन",
  karan: "कौलव",
  rahuKaal: "04:10 PM - 05:26 PM",
  abhijit: "11:59 AM - 12:39 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:05 AM",
  sunset: "05:25 PM",
  moonrise: "10:44 AM",
  moonset: "11:00 PM",
  rashi: "धनु",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-14": {
  tithi: "मार्गशीर्ष शुक्ल चतुर्थी",
  nakshatra: "उत्तराषाढ़ा",
  yog: "अतिगंड",
  karan: "तैतिल",
  rahuKaal: "08:22 AM - 09:40 AM",
  abhijit: "12:00 PM - 12:40 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:05 AM",
  sunset: "05:26 PM",
  moonrise: "11:55 AM",
  moonset: "12:10 AM",
  rashi: "मकर",
  fast: ["विनायक चतुर्थी व्रत"],
  festival: "विनायक चतुर्थी",
  governmentHoliday: ""
},

"2026-12-15": {
  tithi: "मार्गशीर्ष शुक्ल पञ्चमी",
  nakshatra: "श्रवण",
  yog: "सुकर्मा",
  karan: "गर",
  rahuKaal: "02:53 PM - 04:10 PM",
  abhijit: "12:00 PM - 12:40 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:06 AM",
  sunset: "05:26 PM",
  moonrise: "01:03 PM",
  moonset: "1:18 AM",
  rashi: "मकर",
  fast: ["विवाह पंचमी"],
  festival: "विवाह पंचमी",
  governmentHoliday: ""
},


"2026-12-16": {
  tithi: "मार्गशीर्ष शुक्ल षष्ठी",
  nakshatra: "धनिष्ठा",
  yog: "धृति",
  karan: "वणिज",
  rahuKaal: "12:17 PM - 01:35 PM",
  abhijit: "12:00 PM - 12:40 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:07 AM",
  sunset: "05:26 PM",
  moonrise: "02:11 PM",
  moonset: "02:27 AM",
  rashi: "कुंभ",
  fast: ["स्कंद षष्ठी"],
  festival: "चम्पा षष्ठी, स्कंद षष्ठी",
  governmentHoliday: ""
},

"2026-12-17": {
  tithi: "मार्गशीर्ष शुक्ल सप्तमी",
  nakshatra: "शतभिषा",
  yog: "शूल",
  karan: "बव",
  rahuKaal: "01:35 PM - 02:54 PM",
  abhijit: "12:01 PM - 12:41 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:07 AM",
  sunset: "05:26 PM",
  moonrise: "03:19 PM",
  moonset: "03:37 AM",
  rashi: "कुंभ",
  fast: [],
  festival: "मित्र सप्तमी",
  governmentHoliday: ""
},

"2026-12-18": {
  tithi: "मार्गशीर्ष शुक्ल अष्टमी",
  nakshatra: "पूर्वाभाद्रपद",
  yog: "गंड",
  karan: "कौलव",
  rahuKaal: "11:00 AM - 12:18 PM",
  abhijit: "12:01 PM - 12:41 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:08 AM",
  sunset: "05:27 PM",
  moonrise: "04:26 PM",
  moonset: "04:47 AM",
  rashi: "मीन",
  fast: ["मासिक दुर्गाष्टमी"],
  festival: "गोपाष्टमी / दुर्गाष्टमी",
  governmentHoliday: ""
},

"2026-12-19": {
  tithi: "मार्गशीर्ष शुक्ल नवमी",
  nakshatra: "उत्तराभाद्रपद",
  yog: "वृद्धि",
  karan: "तैतिल",
  rahuKaal: "09:42 AM - 11:00 AM",
  abhijit: "12:02 PM - 12:42 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:09 AM",
  sunset: "05:27 PM",
  moonrise: "05:35 PM",
  moonset: "05:58 AM",
  rashi: "मीन",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-20": {
  tithi: "मार्गशीर्ष शुक्ल दशमी",
  nakshatra: "रेवती",
  yog: "ध्रुव",
  karan: "गर",
  rahuKaal: "04:12 PM - 05:30 PM",
  abhijit: "12:02 PM - 12:42 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:09 AM",
  sunset: "05:27 PM",
  moonrise: "06:45 PM",
  moonset: "07:11 AM",
  rashi: "मेष",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-21": {
  tithi: "मार्गशीर्ष शुक्ल एकादशी",
  nakshatra: "अश्विनी",
  yog: "व्याघात",
  karan: "वणिज",
  rahuKaal: "08:25 AM - 09:43 AM",
  abhijit: "12:03 PM - 12:43 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:10 AM",
  sunset: "05:28 PM",
  moonrise: "07:55 PM",
  moonset: "08:24 AM",
  rashi: "मेष",
  fast: ["मोक्षदा एकादशी व्रत", "गीता जयंती"],
  festival: "मोक्षदा एकादशी, गीता जयंती",
  governmentHoliday: ""
},

"2026-12-22": {
  tithi: "मार्गशीर्ष शुक्ल द्वादशी",
  nakshatra: "भरणी",
  yog: "हर्षण",
  karan: "बव",
  rahuKaal: "02:56 PM - 04:13 PM",
  abhijit: "12:03 PM - 12:43 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:10 AM",
  sunset: "05:28 PM",
  moonrise: "09:07 PM",
  moonset: "09:37 AM",
  rashi: "मेष",
  fast: ["व्रत पारण"],
  festival: "मोक्षदा एकादशी पारण, प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-12-23": {
  tithi: "मार्गशीर्ष शुक्ल त्रयोदशी",
  nakshatra: "कृत्तिका",
  yog: "वज्र",
  karan: "कौलव",
  rahuKaal: "12:19 PM - 01:37 PM",
  abhijit: "12:04 PM - 12:44 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:11 AM",
  sunset: "05:29 PM",
  moonrise: "10:19 PM",
  moonset: "10:48 AM",
  rashi: "वृषभ",
  fast: ["प्रदोष व्रत"],
  festival: "प्रदोष व्रत",
  governmentHoliday: ""
},

"2026-12-24": {
  tithi: "मार्गशीर्ष शुक्ल चतुर्दशी",
  nakshatra: "रोहिणी",
  yog: "सिद्धि",
  karan: "तैतिल",
  rahuKaal: "01:37 PM - 02:55 PM",
  abhijit: "12:04 PM - 12:44 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:11 AM",
  sunset: "05:29 PM",
  moonrise: "11:30 PM",
  moonset: "11:55 AM",
  rashi: "वृषभ",
  fast: [],
  festival: "क्रिसमस पूर्व संध्या",
  governmentHoliday: ""
},

"2026-12-25": {
  tithi: "मार्गशीर्ष पूर्णिमा",
  nakshatra: "मृगशिरा",
  yog: "व्यतीपात",
  karan: "विष्टि",
  rahuKaal: "11:02 AM - 12:20 PM",
  abhijit: "12:05 PM - 12:45 PM",
  dosh: "पूर्णिमा / भद्रा",
  sunrise: "07:12 AM",
  sunset: "05:30 PM",
  moonrise: "--",
  moonset: "12:57 PM",
  rashi: "मिथुन",
  fast: ["मार्गशीर्ष पूर्णिमा व्रत", "दत्तात्रेय जयन्ती"],
  festival: "मार्गशीर्ष पूर्णिमा, क्रिसमस, दत्तात्रेय जयंती",
  governmentHoliday: "क्रिसमस"
},

"2026-12-26": {
  tithi: "पौष कृष्ण प्रतिपदा",
  nakshatra: "आर्द्रा",
  yog: "वरीयान",
  karan: "बव",
  rahuKaal: "09:44 AM - 11:02 AM",
  abhijit: "12:05 PM - 12:45 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:12 AM",
  sunset: "05:30 PM",
  moonrise: "12:39 AM",
  moonset: "01:54 PM",
  rashi: "मिथुन",
  fast: [],
  festival: "पौष मास प्रारंभ (उत्तर भारत)",
  governmentHoliday: ""
},

"2026-12-27": {
  tithi: "पौष कृष्ण द्वितीया",
  nakshatra: "पुनर्वसु",
  yog: "परिघ",
  karan: "कौलव",
  rahuKaal: "04:14 PM - 05:31 PM",
  abhijit: "12:05 PM - 12:45 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:13 AM",
  sunset: "05:31 PM",
  moonrise: "01:46 AM",
  moonset: "02:44 PM",
  rashi: "कर्क",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-28": {
  tithi: "पौष कृष्ण तृतीया",
  nakshatra: "पुष्य",
  yog: "शिव",
  karan: "तैतिल",
  rahuKaal: "08:27 AM - 09:45 AM",
  abhijit: "12:06 PM - 12:46 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:13 AM",
  sunset: "05:32 PM",
  moonrise: "02:51 AM",
  moonset: "03:29 PM",
  rashi: "कर्क",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-29": {
  tithi: "पौष कृष्ण चतुर्थी",
  nakshatra: "आश्लेषा",
  yog: "सिद्ध",
  karan: "गर",
  rahuKaal: "02:58 PM - 04:15 PM",
  abhijit: "12:06 PM - 12:46 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:14 AM",
  sunset: "05:32 PM",
  moonrise: "03:55 AM",
  moonset: "04:09 PM",
  rashi: "कर्क",
  fast: ["संकष्टी चतुर्थी व्रत"],
  festival: "संकष्टी गणेश चतुर्थी",
  governmentHoliday: ""
},

"2026-12-30": {
  tithi: "पौष कृष्ण पञ्चमी",
  nakshatra: "मघा",
  yog: "साध्य",
  karan: "वणिज",
  rahuKaal: "12:21 PM - 01:39 PM",
  abhijit: "12:06 PM - 12:46 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:14 AM",
  sunset: "05:33 PM",
  moonrise: "04:57 AM",
  moonset: "04:47 PM",
  rashi: "सिंह",
  fast: [],
  festival: "",
  governmentHoliday: ""
},

"2026-12-31": {
  tithi: "पौष कृष्ण षष्ठी",
  nakshatra: "पूर्वा फाल्गुनी",
  yog: "शुभ",
  karan: "बव",
  rahuKaal: "01:39 PM - 02:58 PM",
  abhijit: "12:07 PM - 12:47 PM",
  dosh: "कोई विशेष दोष नहीं",
  sunrise: "07:14 AM",
  sunset: "05:33 PM",
  moonrise: "05:58 AM",
  moonset: "05:22 PM",
  rashi: "सिंह",
  fast: [],
  festival: "वर्ष का अंतिम दिन (New Year's Eve)",
  governmentHoliday: ""
}

};
